//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeepr.WPF.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeKeepr.WPF.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance:.
        /// </summary>
        public static string Balance_txt {
            get {
                return ResourceManager.GetString("Balance_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to define the categories.
        /// </summary>
        public static string Categories_help {
            get {
                return ResourceManager.GetString("Categories_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories menu.
        /// </summary>
        public static string Categories_menu {
            get {
                return ResourceManager.GetString("Categories_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Category_add {
            get {
                return ResourceManager.GetString("Category_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add the new category.
        /// </summary>
        public static string Category_add_help {
            get {
                return ResourceManager.GetString("Category_add_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been added..
        /// </summary>
        public static string Category_added {
            get {
                return ResourceManager.GetString("Category_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the category.
        /// </summary>
        public static string Category_choose {
            get {
                return ResourceManager.GetString("Category_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clcik to choose the category.
        /// </summary>
        public static string Category_choose_help {
            get {
                return ResourceManager.GetString("Category_choose_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Category_delete {
            get {
                return ResourceManager.GetString("Category_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to delete the chosen category.
        /// </summary>
        public static string Category_delete_help {
            get {
                return ResourceManager.GetString("Category_delete_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category is deleted..
        /// </summary>
        public static string Category_deleted {
            get {
                return ResourceManager.GetString("Category_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Dropdown.
        /// </summary>
        public static string Category_dropdown {
            get {
                return ResourceManager.GetString("Category_dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category by that name already exists. Please try another..
        /// </summary>
        public static string Category_exists {
            get {
                return ResourceManager.GetString("Category_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the category to add or to modify.
        /// </summary>
        public static string Category_name_help {
            get {
                return ResourceManager.GetString("Category_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such category. Please add a new one or chose another..
        /// </summary>
        public static string Category_notexist {
            get {
                return ResourceManager.GetString("Category_notexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Category_update {
            get {
                return ResourceManager.GetString("Category_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to modify the category.
        /// </summary>
        public static string Category_update_help {
            get {
                return ResourceManager.GetString("Category_update_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been updated..
        /// </summary>
        public static string Category_updated {
            get {
                return ResourceManager.GetString("Category_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a category before beginning..
        /// </summary>
        public static string CategoryChoose_error {
            get {
                return ResourceManager.GetString("CategoryChoose_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the app.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to close this app.
        /// </summary>
        public static string Close_help {
            get {
                return ResourceManager.GetString("Close_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Email_hlelp {
            get {
                return ResourceManager.GetString("Email_hlelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email_txt {
            get {
                return ResourceManager.GetString("Email_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you exit, your progress will not be saved.
        ///Exit anyway?.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to expand the registration menu.
        /// </summary>
        public static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Expander.
        /// </summary>
        public static string Expander_title {
            get {
                return ResourceManager.GetString("Expander_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to TimeKeepr? Create a login here:.
        /// </summary>
        public static string Expander_txt {
            get {
                return ResourceManager.GetString("Expander_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string FirstName_txt {
            get {
                return ResourceManager.GetString("FirstName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        public static string FullName_txt {
            get {
                return ResourceManager.GetString("FullName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to access the about menu.
        /// </summary>
        public static string Help_help {
            get {
                return ResourceManager.GetString("Help_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About menu.
        /// </summary>
        public static string Help_menu {
            get {
                return ResourceManager.GetString("Help_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours per Week.
        /// </summary>
        public static string HoursPerWeek {
            get {
                return ResourceManager.GetString("HoursPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of hours you work per week.
        /// </summary>
        public static string HoursPerWeek_help {
            get {
                return ResourceManager.GetString("HoursPerWeek_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Per Week:.
        /// </summary>
        public static string HoursPerWeek_txt {
            get {
                return ResourceManager.GetString("HoursPerWeek_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this if the category you are adding or modifying is an active category.
        /// </summary>
        public static string IsActive_help {
            get {
                return ResourceManager.GetString("IsActive_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this box if this is a meeting.
        /// </summary>
        public static string IsMeeting_help {
            get {
                return ResourceManager.GetString("IsMeeting_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours in meeting.
        /// </summary>
        public static string IsMeeting_hours {
            get {
                return ResourceManager.GetString("IsMeeting_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a meeting?.
        /// </summary>
        public static string IsMeeting_question {
            get {
                return ResourceManager.GetString("IsMeeting_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string LastName_help {
            get {
                return ResourceManager.GetString("LastName_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string LastName_txt {
            get {
                return ResourceManager.GetString("LastName_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to access the logging menu.
        /// </summary>
        public static string Logging_help {
            get {
                return ResourceManager.GetString("Logging_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging menu.
        /// </summary>
        public static string Logging_menu {
            get {
                return ResourceManager.GetString("Logging_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login button.
        /// </summary>
        public static string Login_button {
            get {
                return ResourceManager.GetString("Login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLick here to submit your login information.
        /// </summary>
        public static string Login_help {
            get {
                return ResourceManager.GetString("Login_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string Login_txt {
            get {
                return ResourceManager.GetString("Login_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeKeepr - Login.
        /// </summary>
        public static string Login_window_title {
            get {
                return ResourceManager.GetString("Login_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time spent in meetings - header.
        /// </summary>
        public static string Meetings_header {
            get {
                return ResourceManager.GetString("Meetings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours in Meetings, per Category.
        /// </summary>
        public static string Meetings_title {
            get {
                return ResourceManager.GetString("Meetings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following table lists the number of hours in meetings per category.
        /// </summary>
        public static string Meetings_txt {
            get {
                return ResourceManager.GetString("Meetings_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the application.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to minimize the application.
        /// </summary>
        public static string Minimize_help {
            get {
                return ResourceManager.GetString("Minimize_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password here.
        /// </summary>
        public static string Password_help {
            get {
                return ResourceManager.GetString("Password_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password..
        /// </summary>
        public static string Password_notcorrect {
            get {
                return ResourceManager.GetString("Password_notcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password_txt {
            get {
                return ResourceManager.GetString("Password_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous overtime.
        /// </summary>
        public static string PreviousSaldo {
            get {
                return ResourceManager.GetString("PreviousSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of previous overtime hours you have, if any.
        /// </summary>
        public static string PreviousSaldo_help {
            get {
                return ResourceManager.GetString("PreviousSaldo_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous overtime hours:.
        /// </summary>
        public static string PreviousSaldo_txt {
            get {
                return ResourceManager.GetString("PreviousSaldo_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register button.
        /// </summary>
        public static string Register_but {
            get {
                return ResourceManager.GetString("Register_but", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register / Login.
        /// </summary>
        public static string Register_button {
            get {
                return ResourceManager.GetString("Register_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to register and log in.
        /// </summary>
        public static string Register_help {
            get {
                return ResourceManager.GetString("Register_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Task.
        /// </summary>
        public static string Register_task {
            get {
                return ResourceManager.GetString("Register_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click when you&apos;re finished to register your task.
        /// </summary>
        public static string Register_task_help {
            get {
                return ResourceManager.GetString("Register_task_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your task.
        /// </summary>
        public static string Register_task_txt {
            get {
                return ResourceManager.GetString("Register_task_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register the time in the format xx.xx.
        /// </summary>
        public static string Register_time {
            get {
                return ResourceManager.GetString("Register_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register:.
        /// </summary>
        public static string Register_txt {
            get {
                return ResourceManager.GetString("Register_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click when you&apos;re finished to register your workday.
        /// </summary>
        public static string Register_workday_help {
            get {
                return ResourceManager.GetString("Register_workday_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your workday.
        /// </summary>
        public static string Register_workday_txt {
            get {
                return ResourceManager.GetString("Register_workday_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected or New Category.
        /// </summary>
        public static string Selected_category {
            get {
                return ResourceManager.GetString("Selected_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Task.
        /// </summary>
        public static string Start_task {
            get {
                return ResourceManager.GetString("Start_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to start your task.
        /// </summary>
        public static string Start_task_help {
            get {
                return ResourceManager.GetString("Start_task_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the task.
        /// </summary>
        public static string Start_task_txt {
            get {
                return ResourceManager.GetString("Start_task_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Work.
        /// </summary>
        public static string Start_work {
            get {
                return ResourceManager.GetString("Start_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to begin your workday.
        /// </summary>
        public static string Start_work_help {
            get {
                return ResourceManager.GetString("Start_work_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the workday.
        /// </summary>
        public static string Start_work_txt {
            get {
                return ResourceManager.GetString("Start_work_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to access your statistics.
        /// </summary>
        public static string Statistics_help {
            get {
                return ResourceManager.GetString("Statistics_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics menu.
        /// </summary>
        public static string Statistics_menu {
            get {
                return ResourceManager.GetString("Statistics_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Task.
        /// </summary>
        public static string Stop_task {
            get {
                return ResourceManager.GetString("Stop_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to stop your task.
        /// </summary>
        public static string Stop_task_help {
            get {
                return ResourceManager.GetString("Stop_task_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the task.
        /// </summary>
        public static string Stop_task_txt {
            get {
                return ResourceManager.GetString("Stop_task_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Work.
        /// </summary>
        public static string Stop_work {
            get {
                return ResourceManager.GetString("Stop_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to stop your workday.
        /// </summary>
        public static string Stop_work_help {
            get {
                return ResourceManager.GetString("Stop_work_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the workday.
        /// </summary>
        public static string Stop_work_txt {
            get {
                return ResourceManager.GetString("Stop_work_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must register valid times - please try again..
        /// </summary>
        public static string Time_error {
            get {
                return ResourceManager.GetString("Time_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeKeepr.
        /// </summary>
        public static string TimeKeepr_txt {
            get {
                return ResourceManager.GetString("TimeKeepr_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours.
        /// </summary>
        public static string Total_hours {
            get {
                return ResourceManager.GetString("Total_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information - header.
        /// </summary>
        public static string User_info_header {
            get {
                return ResourceManager.GetString("User_info_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following information pertains to the current user&apos;s information.
        /// </summary>
        public static string User_info_help {
            get {
                return ResourceManager.GetString("User_info_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such user..
        /// </summary>
        public static string User_notexist {
            get {
                return ResourceManager.GetString("User_notexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username here.
        /// </summary>
        public static string Username_help {
            get {
                return ResourceManager.GetString("Username_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username_txt {
            get {
                return ResourceManager.GetString("Username_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week nr..
        /// </summary>
        public static string WeekNr {
            get {
                return ResourceManager.GetString("WeekNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to begin your Work Day before you can start a project..
        /// </summary>
        public static string WorkBegin_error {
            get {
                return ResourceManager.GetString("WorkBegin_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday.
        /// </summary>
        public static string Workday {
            get {
                return ResourceManager.GetString("Workday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work hours per week - header.
        /// </summary>
        public static string WorkPerWeek_header {
            get {
                return ResourceManager.GetString("WorkPerWeek_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Work Hours Per Week.
        /// </summary>
        public static string WorkPerWeek_title {
            get {
                return ResourceManager.GetString("WorkPerWeek_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following table lists the number of work hours per week.
        /// </summary>
        public static string WorkPerWeek_txt {
            get {
                return ResourceManager.GetString("WorkPerWeek_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work hours per week per category - header.
        /// </summary>
        public static string WorkPerWeekCategory_header {
            get {
                return ResourceManager.GetString("WorkPerWeekCategory_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours Per Week, per Category.
        /// </summary>
        public static string WorkPerWeekCategory_title {
            get {
                return ResourceManager.GetString("WorkPerWeekCategory_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following table lists the number of work hours per week per category.
        /// </summary>
        public static string WorkPerWeekCategory_txt {
            get {
                return ResourceManager.GetString("WorkPerWeekCategory_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        public static string Workplace {
            get {
                return ResourceManager.GetString("Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of your workplace.
        /// </summary>
        public static string Workplace_help {
            get {
                return ResourceManager.GetString("Workplace_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace:.
        /// </summary>
        public static string Workplace_txt {
            get {
                return ResourceManager.GetString("Workplace_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Task.
        /// </summary>
        public static string Worktask {
            get {
                return ResourceManager.GetString("Worktask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
